interface TechnicalSpecificationsProps {
  variant: string;
  productId?: string;
}

export default function TechnicalSpecifications({ variant, productId }: TechnicalSpecificationsProps) {
  // Use the variant prop directly - it's already in the correct format (e.g., "4-pin", "6-pin")
  // For standalone products without variants, use productId as the key
  const specKey = variant === "default" && productId ? productId : variant;
  const specs = {
    "4-pin": {
      pins: "4 + PE",
      current: "25–40 A",
      voltage: "500–690 V AC",
      impulseVoltage: "6–8 kV",
      pinMaterial: "Copper Alloy (Silver/Gold Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw / Crimp",
      wireSpec: "1.0–10.0 mm²",
      torque: "0.6–0.9 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Die-Cast Aluminum Alloy / Zinc Alloy",
      protection: "IP65 / IP67",
      sealing: "NBR / Silicone",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48–72 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    "6-pin": {
      pins: "6 + PE",
      current: "16–40 A",
      voltage: "500–690 V AC",
      impulseVoltage: "6–8 kV",
      pinMaterial: "Copper Alloy (Silver/Gold Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw / Crimp",
      wireSpec: "1.0–6.0 mm²",
      torque: "0.5–0.8 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Die-Cast Aluminum Alloy / Zinc Alloy",
      protection: "IP65 / IP67",
      sealing: "NBR / Silicone",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48–72 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    "hd-6": {
      pins: "6 + PE",
      current: "16–40 A",
      voltage: "500–690 V AC",
      impulseVoltage: "6–8 kV",
      pinMaterial: "Copper Alloy (Silver/Gold Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw/Crimp",
      wireSpec: "1.0–6.0 mm²",
      torque: "0.5–0.8 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Die-Cast Aluminum / Zinc Alloy",
      protection: "IP65/IP67",
      sealing: "NBR / Silicone",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48–72 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel / Inline / Cable-to-Cable"
    },
    "7-pin": {
      pins: "7 + PE",
      current: "20–32 A",
      voltage: "500 V AC",
      impulseVoltage: "6 kV",
      pinMaterial: "Copper Alloy (Silver Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw / Crimp",
      wireSpec: "1.0–6.0 mm²",
      torque: "0.5–0.8 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Aluminum Alloy / Thermoplastic",
      protection: "IP65",
      sealing: "Silicone / NBR",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    "10-pin": {
      pins: "10 + PE",
      current: "16–25 A",
      voltage: "500 V AC",
      impulseVoltage: "6 kV",
      pinMaterial: "Copper Alloy (Silver Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw / Crimp",
      wireSpec: "0.75–4.0 mm²",
      torque: "0.5–0.6 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Aluminum Alloy / Thermoplastic",
      protection: "IP65",
      sealing: "Silicone / NBR",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    "hd-10": {
      pins: "10 + PE",
      current: "10–16 A",
      voltage: "250–500 V AC",
      impulseVoltage: "6–8 kV",
      pinMaterial: "Copper Alloy (Silver/Gold Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw / Crimp",
      wireSpec: "0.75–2.5 mm²",
      torque: "0.5–0.8 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Die-Cast Aluminum / Zinc Alloy",
      protection: "IP65 / IP67",
      sealing: "NBR / Silicone",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48–72 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel / Inline / Cable-to-Cable"
    },
    "16-pin": {
      pins: "16 + PE",
      current: "16 A",
      voltage: "500 V AC",
      impulseVoltage: "6 kV",
      pinMaterial: "Copper (Silver/Gold Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw",
      wireSpec: "0.5–4.0 mm²",
      torque: "0.5 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Die-Cast Aluminum",
      protection: "IP65",
      sealing: "NBR",
      locking: "Metal Roller / Double Buckle",
      saltSpray: "48 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    "hd-16": {
      pins: "16 + PE",
      current: "10 A",
      voltage: "250–500 V AC",
      impulseVoltage: "6–8 kV",
      pinMaterial: "Copper Alloy (Silver/Gold Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw / Crimp",
      wireSpec: "0.75–2.5 mm²",
      torque: "0.5–0.8 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Die-Cast Aluminum / Zinc Alloy",
      protection: "IP65 / IP67",
      sealing: "NBR / Silicone",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48–72 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel / Inline / Cable-to-Cable"
    },
    "24-pin": {
      pins: "24 (2×12 rows)",
      current: "16 A",
      voltage: "250–1000 V",
      impulseVoltage: "up to 6 kV",
      pinMaterial: "Copper Alloy (Gold/Tin Plated)",
      contactResistance: "< 10 mΩ",
      wiringForm: "Crimp / Solder",
      wireSpec: "0.5–2.5 mm²",
      torque: "0.5–0.6 Nm",
      matingCycles: "500–1000",
      temperature: "-40°C to +125°C",
      shellMaterial: "Nylon / Zinc Alloy / Thermoplastic",
      protection: "IP67 / IP68",
      sealing: "Silicone Gasket",
      locking: "Twist Lock / Bayonet / Threaded",
      saltSpray: "48 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    "hd-24": {
      pins: "24 + PE",
      current: "10 A",
      voltage: "250–500 V AC",
      impulseVoltage: "6–8 kV",
      pinMaterial: "Copper Alloy (Silver/Gold Plated)",
      contactResistance: "≤ 1 mΩ",
      wiringForm: "Screw / Crimp",
      wireSpec: "0.75–2.5 mm²",
      torque: "0.5–0.8 Nm",
      matingCycles: "≥ 500",
      temperature: "-40°C to +125°C",
      shellMaterial: "Die-Cast Aluminum / Zinc Alloy",
      protection: "IP65 / IP67",
      sealing: "NBR / Silicone",
      locking: "Double Latch / Screw Lock",
      saltSpray: "48–72 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel / Inline / Cable-to-Cable"
    },
    "32-pin": {
      pins: "32 + PE",
      current: "10–16 A",
      voltage: "250–500 V",
      impulseVoltage: "4–6 kV",
      pinMaterial: "Copper Alloy (Tin Plated)",
      contactResistance: "< 10 mΩ",
      wiringForm: "Crimp / Screw",
      wireSpec: "0.5–2.5 mm²",
      torque: "0.4–0.5 Nm",
      matingCycles: "500–1000",
      temperature: "-40°C to +125°C",
      shellMaterial: "Thermoplastic / Zinc Alloy",
      protection: "IP67",
      sealing: "Silicone Rubber",
      locking: "Bayonet / Latch Lock",
      saltSpray: "48 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    "48-pin": {
      pins: "48 (3×16 / 4×12 rows)",
      current: "10 A",
      voltage: "250–500 V",
      impulseVoltage: "4–6 kV",
      pinMaterial: "Copper Alloy (Tin/Gold Plated)",
      contactResistance: "< 10 mΩ",
      wiringForm: "Crimp / Solder",
      wireSpec: "0.25–2.5 mm²",
      torque: "0.4–0.5 Nm",
      matingCycles: "500–1000",
      temperature: "-40°C to +125°C",
      shellMaterial: "Reinforced Thermoplastic / Zinc Alloy",
      protection: "IP67 / IP68",
      sealing: "Silicone Rubber",
      locking: "Bayonet / Threaded / Latch Lock",
      saltSpray: "48 hours",
      humidity: "90% RH at 40°C",
      mounting: "Panel Mount / Inline / Cable-to-Cable"
    },
    // IR Lamp Specifications
    "440mm": {
      length: "440 mm",
      voltage: "220 V AC",
      power: "1.5 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 800°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint Curing, Packaging Machines",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "626mm": {
      length: "626 mm",
      voltage: "230 V AC",
      power: "2.5 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Printing, Powder Coating, Industrial Ovens",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "728mm": {
      length: "728 mm",
      voltage: "415 V AC",
      power: "2.5 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Metal Preheating, Paint Curing, Process Heating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "800mm": {
      length: "800 mm",
      voltage: "440 V AC",
      power: "4.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 900°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Heavy-Duty Heating, Industrial Drying, Curing",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "830mm": {
      length: "830 mm",
      voltage: "230 V AC",
      power: "3.0 kW",
      surface: "One Side Coated",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Directional Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Printing, Packaging, Coating (Directional Heating)",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "850mm": {
      length: "850 mm",
      voltage: "440 V AC",
      power: "4.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 900°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Industrial Ovens, Powder Coating, Process Heating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "875mm": {
      length: "875 mm",
      voltage: "415 V AC",
      power: "3.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Paint Curing, Plastic Drying, Manufacturing",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "1120mm": {
      length: "1120 mm",
      voltage: "415 V AC",
      power: "3.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Wide-Area Heating, Industrial Ovens, Drying Systems",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "1150mm": {
      length: "1150 mm",
      voltage: "440 V AC",
      power: "6.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 950°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Heavy-Duty Industrial Heating, Large Ovens, High-Power Curing",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "1220mm": {
      length: "1220 mm",
      voltage: "415 V AC",
      power: "3.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Conveyor Systems, Continuous Processes, Extended Heating Zones",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "1250mm": {
      length: "1250 mm",
      voltage: "230 V AC",
      power: "4.0 kW",
      surface: "One Side Coated",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Directional Infrared Radiation",
      operatingTemp: "Up to 900°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Large-Scale Industrial Heating, Directional Curing, Wide Ovens",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "foil-1": {
      productName: "ESINTI Digital Hot Foil Stamping Machine",
      printingSize: "4 × 6 inch",
      technology: "Digital temperature & pressure control",
      materialCompatibility: "Paper, cardboard, PVC, leather, coated plastic",
      bodyStructure: "Heavy-duty steel",
      foilTypes: "Gold, Silver, Holographic, Pigmented",
      usageType: "Commercial / Industrial",
      operation: "Semi-Automatic / Digital",
      suitableFor: "Packaging, printing, branding"
    },
    "foil-2": {
      productName: "ESINTI Digital Hot Foil Stamping Machine",
      printingArea: "4 × 6 inch",
      technology: "Digital foil stamping (Heat + Pressure)",
      temperatureControl: "Fully digital controller",
      supportedFoils: "Gold, Silver, Holographic, Pigmented",
      compatibleSurfaces: "Paper, cardboard, PVC, leather, coated materials",
      frameMaterial: "Heavy-duty industrial steel",
      heatingSystem: "High-performance digital heater",
      operationType: "Semi-automatic / Digital control",
      suitableFor: "Commercial printing & craft production"
    },
    "ir-440": {
      length: "440 mm",
      voltage: "220 V AC",
      power: "1.5 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 800°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint Curing, Packaging Machines",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-626": {
      length: "626 mm",
      voltage: "230 V AC",
      power: "2.5 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint & Ink Curing, Powder Coating Systems, Printing & Packaging Machines, Industrial Ovens, Metal Preheating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-728": {
      length: "728 mm",
      voltage: "415 V AC",
      power: "2.5 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint Curing, Powder Coating Lines, Printing & Packaging, Metal Preheating, Industrial Heating Systems",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-800": {
      length: "800 mm",
      voltage: "440 V AC",
      power: "4.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 900°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint & Ink Curing, Powder Coating Systems, Printing & Packaging Machines, Industrial Ovens, Metal Preheating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-830": {
      length: "830 mm",
      voltage: "230 V AC",
      power: "3.0 kW",
      surface: "One-Side Coated",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Directional Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Directional heating systems, High-precision thermal curing, Plastic molding & drying, Industrial ovens, Conveyor heating lines",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-850": {
      length: "850 mm",
      voltage: "440 V AC",
      power: "4.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 900°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint & Ink Curing, Powder Coating Systems, Printing & Packaging Machines, Industrial Ovens, Metal Preheating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-875": {
      length: "875 mm",
      voltage: "415 V AC",
      power: "3.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint & Ink Curing, Powder Coating Systems, Printing & Packaging Machines, Industrial Ovens, Metal Preheating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-1120": {
      length: "1120 mm",
      voltage: "415 V AC",
      power: "3.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint & Ink Curing, Powder Coating Systems, Printing & Packaging Machines, Industrial Ovens, Metal Preheating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-1150": {
      length: "1150 mm",
      voltage: "440 V AC",
      power: "6.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 950°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Heavy industrial curing, Powder coating ovens, Metal preheating lines, Printing & drying tunnels",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-1220": {
      length: "1220 mm",
      voltage: "415 V AC",
      power: "3.0 kW",
      surface: "Clear Tube",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Infrared Radiation",
      operatingTemp: "Up to 850°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Plastic Drying, Paint & Ink Curing, Powder Coating Systems, Printing & Packaging Machines, Industrial Ovens, Metal Preheating",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "ir-1250": {
      length: "1250 mm",
      voltage: "230 V AC",
      power: "4.0 kW",
      surface: "One-Side Coated",
      material: "Ceramic Insulation",
      heatingElement: "Quartz Tube",
      heatTransfer: "Directional Infrared Radiation",
      operatingTemp: "Up to 900°C",
      responseTime: "< 30 seconds",
      energyEfficiency: "High",
      serviceLife: "> 5000 hours",
      applications: "Directional thermal curing, High-efficiency industrial drying, Packaging & printing machines, Heat-intensive production units",
      mounting: "Horizontal / Vertical",
      cooling: "Natural Convection"
    },
    "uv-805": {
      totalLength: "805 mm",
      arcLength: "635 mm",
      diameter: "25 mm",
      endFitting: "B",
      terminalType: "Pin Type",
      cableLength: "285/285 mm",
      voltage: "900V",
      current: "8.8A",
      power: "7.5kW"
    },
    "uv-812": {
      totalLength: "812 mm",
      arcLength: "711 mm",
      diameter: "25 mm",
      endFitting: "B",
      terminalType: "Pin Type",
      cableLength: "285/285 mm",
      voltage: "1000V",
      current: "8.4A",
      power: "8.4kW"
    },
    "uv-914": {
      totalLength: "914 mm",
      arcLength: "762 mm",
      diameter: "25 mm",
      endFitting: "B",
      terminalType: "Pin Type",
      cableLength: "285/285 mm",
      voltage: "1000V",
      current: "9.8A",
      power: "9.0kW"
    },
    "uv-1016": {
      totalLength: "1016 mm",
      arcLength: "914 mm",
      diameter: "25 mm",
      endFitting: "B",
      terminalType: "Pin Type",
      cableLength: "285/285 mm",
      voltage: "1200V",
      current: "9A",
      power: "10.8kW"
    },
    "uv-1168": {
      totalLength: "1168 mm",
      arcLength: "1016 mm",
      diameter: "25 mm",
      endFitting: "B",
      terminalType: "Pin Type",
      cableLength: "285/285 mm",
      voltage: "1500V",
      current: "10.6A",
      power: "16kW"
    },
    "gear-1": {
      model: "78ZR5-750T1",
      gearType: "Helical Planetary Gearbox",
      reductionRatio: "5:1 (Single Stage)",
      stages: "1-stage",
      ratedOutputTorque: "330 N·m",
      instantTorque: "990 N·m",
      compatibleMotorPower: "750 W (NEMA 42 compatible)",
      backlash: "≤ 3 arc-minutes",
      efficiency: "96–97%",
      noiseLevel: "≤ 60 dB (Measured at L=100 cm)",
      lifespan: "30,000 hours",
      material: "High-grade Steel (Hardened)",
      weight: "8.1 kg",
      mounting: "Flange Mount",
      protectionGrade: "IP65",
      operatingTemp: "-25°C to +90°C",
      lubrication: "Lifetime lubrication",
      packaging: "Box / Carton"
    },
    "tresu-1": {
      productName: "TRESU Coater Rubber",
      material: "High-Grade Industrial Rubber",
      color: "Black",
      application: "Printing Machines, Coaters, Laminators",
      usage: "Coater Rollers & Doctor Blade Systems",
      innerDiameter: "3 inch",
      resistance: "Heat, Pressure & Chemical Resistant",
      packaging: "Box / Carton",
      brand: "TRESU"
    },
    "pump-aro-66605j": {
      brand: "ARO",
      modelNo: "66605J-3EB",
      pumpType: "Air Operated Double Diaphragm Pump (AODD)",
      inletOutletSize: "1/2\" (Dual Inlet & Outlet)",
      maxFlowRate: "49 – 50 LPM",
      materialOfConstruction: "Polypropylene (PP) & Teflon (PTFE)",
      wettedParts: "Polypropylene (PP)",
      diaphragmMaterial: "PTFE / Teflon",
      powerSource: "Pneumatic (Compressed Air)",
      operation: "Non-Electric, Air-Operated",
      temperatureResistance: "Suitable for industrial room-temperature & chemical fluids",
      idealFor: "Corrosive liquids, adhesives, inks, coatings, chemicals",
      mounting: "Universal industrial mount",
      weight: "Lightweight PP body"
    },
    "clamp-1": {
      productName: "IR Round Clamp / Infrared Lamp Mounting Clamp",
      shape: "Round (for tubular IR lamps)",
      material: "Stainless Steel / Heat-Resistant Alloy",
      surfaceFinish: "Polished / Anti-rust Coating",
      temperatureResistance: "Up to 500°C (continuous use)",
      mountingType: "Screw / Bolt-on",
      compatibility: "Short-wave, Medium-wave, Fast-response IR Lamps",
      durability: "Long service life, corrosion resistant",
      applications: "Printing, Packaging, Textile Drying, Plastic Thermoforming, Food Processing"
    },
    "clamp-2": {
      productName: "IR Square Clamp / Infrared Tube Mounting Clamp",
      shape: "Square (for tube-shaped IR lamps)",
      material: "Stainless Steel / Heat-Resistant Alloy",
      variants: "Ceramic & Quartz Clamp Options",
      surfaceFinish: "Polished / Anti-rust Coating",
      color: "Silver",
      temperatureResistance: "Up to 500°C (continuous use)",
      mountingType: "Screw / Bolt-on",
      compatibility: "IR Drying Lamps & Tubes (Ceramic & Quartz holders)",
      durability: "High strength, long-lasting, stable grip",
      applications: "Offset Printing, Flexo & Gravure Printing, Coating & Drying Units, Packaging Machinery, Electronics & Plastic Curing"
    },
    "ballast-1": {
      model: "HVTA-400-9-1000",
      power: "9 kW",
      voltage: "1000 V",
      displayType: "Digital",
      ballastType: "Electronic",
      shape: "Rectangle",
      connectivity: "Ethernet / RS485",
      usage: "UV Ballast for UV Curing Systems",
      protection: "Overload, Short-Circuit, Overheat",
      industrialUse: "24/7 Continuous Operation"
    },
    "ballast-2": {
      model: "HVTA-400-12-1350",
      power: "12 kW",
      voltage: "1350 V",
      displayType: "Digital",
      ballastType: "Electronic",
      shape: "Rectangle",
      connectivity: "Ethernet / RS485",
      usage: "UV Ballast for UV Curing Systems",
      protection: "Overload, Short-Circuit, Overheat",
      industrialUse: "24/7 Continuous Operation"
    },
    "ballast-3": {
      model: "HVTA-400-16-1500",
      power: "16 kW",
      voltage: "1500 V",
      displayType: "Digital",
      ballastType: "Electronic",
      shape: "Rectangle",
      connectivity: "Ethernet / RS485",
      usage: "UV Ballast for UV Curing Systems",
      protection: "Overload, Short-Circuit, Overheat",
      industrialUse: "24/7 Heavy-Duty Operation"
    },
    "encoder-1": {
      productName: "Shaft Encoder BI-38-H8-2500-PU",
      modelNo: "BI-38-H8-2500-PU",
      encoderType: "Incremental Rotary Encoder",
      bodyDiameter: "38 mm",
      shaftDiameter: "8 mm",
      resolution: "2500 PPR",
      outputType: "Push-Pull (HTL)",
      operatingVoltage: "5–24V DC",
      applicationAreas: "CNC Machinery, Robotics, Automated Conveyors, Printing Machines, Motion Control Systems",
      keyFeatures: "High Accuracy, Noise-Resistant Output, Rugged & Reliable Design, Easy Installation"
    },
    "encoder-2": {
      coreMaterial: "Stainless Steel (CNC-machined, polished finish)",
      outerMaterial: "High-Performance Polyurethane (PU)",
      outerDiameter: "50 mm – 100 mm",
      boreDiameter: "6 mm – 20 mm",
      thickness: "8 mm – 20 mm",
      hardness: "85 – 95 Shore A",
      operatingTemperature: "-20°C to +80°C",
      surfaceFinish: "Smooth, wear-resistant, low-noise",
      encoderType: "Rotary",
      usage: "Industrial Applications"
    },
    "encoder-3": {
      material: "Stainless Steel / Aluminum",
      mainFrame: "Parallel side plates with precision-machined mounting holes",
      shafts: "Dual cylindrical shafts for roller & rotating part support",
      clampBlocks: "Aluminum blocks with circular cutouts + clamping screws",
      springs: "Tension springs for adjustable force & automatic return",
      encoderType: "Rotary",
      surfaceFinish: "Polished / Powder-coated (corrosion-resistant)",
      operatingTemperature: "-20°C to +80°C",
      usage: "Industrial rotary encoder mounting assemblies"
    }
  };

  const currentSpecs = specs[specKey as keyof typeof specs] || specs["4-pin"];
  
  // Determine if this is an IR Lamp, Connector, Foil Machine, UV Lamp, Gearbox, TRESU Rubber, Pump, IR Clamp, Ballast, or Encoder based on the spec keys
  const isIRLamp = currentSpecs && 'length' in currentSpecs;
  const isFoilMachine = currentSpecs && 'productName' in currentSpecs && !('brand' in currentSpecs) && !('shape' in currentSpecs) && !('encoderType' in currentSpecs) && !('coreMaterial' in currentSpecs) && !('material' in currentSpecs);
  const isUVLamp = currentSpecs && 'totalLength' in currentSpecs;
  const isGearbox = currentSpecs && 'gearType' in currentSpecs;
  const isTresuRubber = currentSpecs && 'brand' in currentSpecs && (currentSpecs as any).brand === 'TRESU';
  const isPump = currentSpecs && 'pumpType' in currentSpecs;
  const isIRClamp = currentSpecs && 'shape' in currentSpecs && (currentSpecs as any).shape.includes('Round');
  const isIRSquareClamp = currentSpecs && 'shape' in currentSpecs && (currentSpecs as any).shape.includes('Square');
  const isBallast = currentSpecs && 'ballastType' in currentSpecs;
  const isEncoder = currentSpecs && 'encoderType' in currentSpecs && 'modelNo' in currentSpecs;
  const isEncoderWheel = currentSpecs && 'coreMaterial' in currentSpecs;
  const isEncoderBracket = currentSpecs && 'mainFrame' in currentSpecs;

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-secondary">Technical Specifications</h2>
      
      <div className="overflow-x-auto">
        <table className="w-full border-collapse bg-white rounded-lg overflow-hidden shadow-sm">
          <thead>
            <tr className="bg-gradient-primary text-white">
              <th className="px-4 py-3 text-left font-semibold">Parameter</th>
              <th className="px-4 py-3 text-left font-semibold">Specification</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(
              isEncoderBracket ? {
                "Material": (currentSpecs as any).material,
                "Main Frame": (currentSpecs as any).mainFrame,
                "Shafts / Rods": (currentSpecs as any).shafts,
                "Clamp Blocks": (currentSpecs as any).clampBlocks,
                "Springs": (currentSpecs as any).springs,
                "Encoder Type": (currentSpecs as any).encoderType,
                "Surface Finish": (currentSpecs as any).surfaceFinish,
                "Operating Temperature": (currentSpecs as any).operatingTemperature,
                "Usage": (currentSpecs as any).usage,
              } : isEncoderWheel ? {
                "Core Material": (currentSpecs as any).coreMaterial,
                "Outer Material": (currentSpecs as any).outerMaterial,
                "Outer Diameter (OD)": (currentSpecs as any).outerDiameter,
                "Bore Diameter": (currentSpecs as any).boreDiameter,
                "Thickness / Width": (currentSpecs as any).thickness,
                "Hardness (PU)": (currentSpecs as any).hardness,
                "Operating Temperature": (currentSpecs as any).operatingTemperature,
                "Surface Finish": (currentSpecs as any).surfaceFinish,
                "Encoder Type": (currentSpecs as any).encoderType,
                "Usage": (currentSpecs as any).usage,
              } : isEncoder ? {
                "Product Name": (currentSpecs as any).productName,
                "Model No": (currentSpecs as any).modelNo,
                "Encoder Type": (currentSpecs as any).encoderType,
                "Body Diameter": (currentSpecs as any).bodyDiameter,
                "Shaft Diameter": (currentSpecs as any).shaftDiameter,
                "Resolution": (currentSpecs as any).resolution,
                "Output Type": (currentSpecs as any).outputType,
                "Operating Voltage": (currentSpecs as any).operatingVoltage,
                "Application Areas": (currentSpecs as any).applicationAreas,
                "Key Features": (currentSpecs as any).keyFeatures,
              } : isBallast ? {
                "Model": (currentSpecs as any).model,
                "Power": (currentSpecs as any).power,
                "Voltage": (currentSpecs as any).voltage,
                "Display Type": (currentSpecs as any).displayType,
                "Ballast Type": (currentSpecs as any).ballastType,
                "Shape": (currentSpecs as any).shape,
                "Connectivity": (currentSpecs as any).connectivity,
                "Usage": (currentSpecs as any).usage,
                "Protection": (currentSpecs as any).protection,
                "Industrial Use": (currentSpecs as any).industrialUse,
              } : isIRSquareClamp ? {
                "Product Name": (currentSpecs as any).productName,
                "Shape": (currentSpecs as any).shape,
                "Material": (currentSpecs as any).material,
                "Variants": (currentSpecs as any).variants,
                "Surface Finish": (currentSpecs as any).surfaceFinish,
                "Color": (currentSpecs as any).color,
                "Temperature Resistance": (currentSpecs as any).temperatureResistance,
                "Mounting Type": (currentSpecs as any).mountingType,
                "Compatibility": (currentSpecs as any).compatibility,
                "Durability": (currentSpecs as any).durability,
                "Applications": (currentSpecs as any).applications,
              } : isIRClamp ? {
                "Product Name": (currentSpecs as any).productName,
                "Shape": (currentSpecs as any).shape,
                "Material": (currentSpecs as any).material,
                "Surface Finish": (currentSpecs as any).surfaceFinish,
                "Temperature Resistance": (currentSpecs as any).temperatureResistance,
                "Mounting Type": (currentSpecs as any).mountingType,
                "Compatibility": (currentSpecs as any).compatibility,
                "Durability": (currentSpecs as any).durability,
                "Applications": (currentSpecs as any).applications,
              } : isPump ? {
                "Brand": (currentSpecs as any).brand,
                "Model No.": (currentSpecs as any).modelNo,
                "Pump Type": (currentSpecs as any).pumpType,
                "Inlet / Outlet Size": (currentSpecs as any).inletOutletSize,
                "Maximum Flow Rate": (currentSpecs as any).maxFlowRate,
                "Material of Construction (MOC)": (currentSpecs as any).materialOfConstruction,
                "Wetted Parts": (currentSpecs as any).wettedParts,
                "Diaphragm Material": (currentSpecs as any).diaphragmMaterial,
                "Power Source": (currentSpecs as any).powerSource,
                "Operation": (currentSpecs as any).operation,
                "Temperature Resistance": (currentSpecs as any).temperatureResistance,
                "Ideal For": (currentSpecs as any).idealFor,
                "Mounting": (currentSpecs as any).mounting,
                "Weight": (currentSpecs as any).weight,
              } : isTresuRubber ? {
                "Product Name": (currentSpecs as any).productName,
                "Material": (currentSpecs as any).material,
                "Color": (currentSpecs as any).color,
                "Application": (currentSpecs as any).application,
                "Usage": (currentSpecs as any).usage,
                "Inner Diameter": (currentSpecs as any).innerDiameter,
                "Resistance": (currentSpecs as any).resistance,
                "Packaging": (currentSpecs as any).packaging,
                "Brand": (currentSpecs as any).brand,
              } : isGearbox ? {
                "Model": (currentSpecs as any).model,
                "Gear Type": (currentSpecs as any).gearType,
                "Reduction Ratio": (currentSpecs as any).reductionRatio,
                "Stages": (currentSpecs as any).stages,
                "Rated Output Torque (T2N)": (currentSpecs as any).ratedOutputTorque,
                "Instant / Stop Torque": (currentSpecs as any).instantTorque,
                "Compatible Motor Power": (currentSpecs as any).compatibleMotorPower,
                "Backlash": (currentSpecs as any).backlash,
                "Efficiency": (currentSpecs as any).efficiency,
                "Noise Level": (currentSpecs as any).noiseLevel,
                "Lifespan": (currentSpecs as any).lifespan,
                "Material": (currentSpecs as any).material,
                "Weight": (currentSpecs as any).weight,
                "Mounting": (currentSpecs as any).mounting,
                "Protection Grade": (currentSpecs as any).protectionGrade,
                "Operating Temperature": (currentSpecs as any).operatingTemp,
                "Lubrication": (currentSpecs as any).lubrication,
                "Packaging": (currentSpecs as any).packaging,
              } : isUVLamp ? {
                "Total Length": (currentSpecs as any).totalLength,
                "Arc Length": (currentSpecs as any).arcLength,
                "Diameter": (currentSpecs as any).diameter,
                "End Fitting": (currentSpecs as any).endFitting,
                "Terminal Type": (currentSpecs as any).terminalType,
                "Cable Length": (currentSpecs as any).cableLength,
                "Voltage": (currentSpecs as any).voltage,
                "Current": (currentSpecs as any).current,
                "Power": (currentSpecs as any).power,
              } : isFoilMachine ? {
                "Product Name": (currentSpecs as any).productName,
                "Printing Size": (currentSpecs as any).printingSize || (currentSpecs as any).printingArea,
                "Technology": (currentSpecs as any).technology,
                "Temperature Control": (currentSpecs as any).temperatureControl,
                "Supported Foils": (currentSpecs as any).supportedFoils,
                "Material Compatibility": (currentSpecs as any).materialCompatibility || (currentSpecs as any).compatibleSurfaces,
                "Body Structure": (currentSpecs as any).bodyStructure,
                "Frame Material": (currentSpecs as any).frameMaterial,
                "Heating System": (currentSpecs as any).heatingSystem,
                "Foil Types": (currentSpecs as any).foilTypes,
                "Usage Type": (currentSpecs as any).usageType,
                "Operation": (currentSpecs as any).operation || (currentSpecs as any).operationType,
                "Suitable For": (currentSpecs as any).suitableFor,
              } : isIRLamp ? {
                "Total Length": (currentSpecs as any).length,
                "Voltage": (currentSpecs as any).voltage,
                "Power Rating": (currentSpecs as any).power,
                "Surface Type": (currentSpecs as any).surface,
                "Insulation Material": (currentSpecs as any).material,
                "Heating Element": (currentSpecs as any).heatingElement,
                "Heat Transfer": (currentSpecs as any).heatTransfer,
                "Operating Temperature": (currentSpecs as any).operatingTemp,
                "Response Time": (currentSpecs as any).responseTime,
                "Energy Efficiency": (currentSpecs as any).energyEfficiency,
                "Service Life": (currentSpecs as any).serviceLife,
                "Applications": (currentSpecs as any).applications,
                "Mounting": (currentSpecs as any).mounting,
                "Cooling": (currentSpecs as any).cooling,
              } : {
                "Number of Pins": (currentSpecs as any).pins,
                "Rated Current": (currentSpecs as any).current,
                "Rated Voltage": (currentSpecs as any).voltage,
                "Rated Impulse Voltage": (currentSpecs as any).impulseVoltage,
                "Pin Material": (currentSpecs as any).pinMaterial,
                "Contact Resistance": (currentSpecs as any).contactResistance,
                "Wiring Form": (currentSpecs as any).wiringForm,
                "Wire Specification": (currentSpecs as any).wireSpec,
                "Tightening Torque": (currentSpecs as any).torque,
                "Mating Cycles": (currentSpecs as any).matingCycles,
                "Operating Temperature": (currentSpecs as any).temperature,
                "Shell Material": (currentSpecs as any).shellMaterial,
                "Protection Grade": (currentSpecs as any).protection,
                "Sealing Element": (currentSpecs as any).sealing,
                "Locking Mechanism": (currentSpecs as any).locking,
                "Salt Spray Resistance": (currentSpecs as any).saltSpray,
                "Humidity Resistance": (currentSpecs as any).humidity,
                "Mounting Style": (currentSpecs as any).mounting,
              }
            ).map(([key, value], index) => (
              <tr 
                key={key}
                className={`border-b border-gray-200 hover:bg-gray-50 transition-colors ${
                  index % 2 === 0 ? 'bg-gray-50/50' : 'bg-white'
                }`}
              >
                <td className="px-4 py-3 font-medium text-gray-700">{key}</td>
                <td className="px-4 py-3 text-gray-900">{value}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
